### ISSUE TITLE
package renaming 

### ISSUE THREAD

**Issue by aspina7** [R4EPI/epitabulate#20]
consider renaming to epigt ? gtepi? 
thoughts feelings arguments @pbkeating @nsbatra @amygimma @zkamvar

**Comment by nsbatra** [comment]
I'd shy away from something with "gt" in case we switch to another
underlying package later. What about epitable?

**Comment by aspina7** [comment]
used to exist - was removed from [CRAN ](https://cran.r-project.org/web/packages/epitable/index.html) but turns out you cant takeover names once they have been used. 
Wonder if would be possible to email the maintainer and take over / overwrite existing stuff there?

Otherwise epicounts?

**Comment by aspina7** [comment]
Epitabulate
